"""
Skill taxonomy + prerequisite graph.

This is the backbone of the recommendation engine: every course in
app/data/courses.json is tagged with one or more of these skill ids, and
every learning path is generated by walking this DAG from what the learner
already knows to the skill that matches their goal.

Each skill node has:
- label:    human readable name
- domain:   which broader track it belongs to (used for the "career path"
            picker on the profile/onboarding screen)
- level:    foundation | core | advanced  (used to order stages)
- keywords: phrases used by the TF-IDF goal matcher to tag free-text goals
- prereqs:  skill ids that must come before this one
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class SkillNode:
    id: str
    label: str
    domain: str
    level: str  # foundation | core | advanced
    keywords: list[str] = field(default_factory=list)
    prereqs: list[str] = field(default_factory=list)


SKILLS: dict[str, SkillNode] = {}


def _add(id_: str, label: str, domain: str, level: str,
         keywords: list[str], prereqs: list[str] | None = None) -> None:
    SKILLS[id_] = SkillNode(id_, label, domain, level, keywords, prereqs or [])


# ---- Programming / CS foundations ----
_add("python_basics", "Python Basics", "programming", "foundation",
     ["python", "programming basics", "intro to programming"])
_add("dsa", "Data Structures & Algorithms", "programming", "core",
     ["data structure", "algorithm", "dsa"], ["python_basics"])
_add("sql_databases", "SQL & Databases", "programming", "foundation",
     ["sql", "database", "mysql", "postgres"])
_add("java_basics", "Java Programming", "programming", "foundation", ["java"])
_add("cpp_basics", "C++ Programming", "programming", "foundation", ["c++", "cpp"])
_add("git_version_control", "Git & Version Control", "programming", "foundation",
     ["git", "github", "version control"])
_add("android_dev", "Android Development", "programming", "core",
     ["android development", "android app"], ["java_basics"])

# ---- Data Science / ML track ----
_add("stats_foundations", "Statistics Foundations", "data_science", "foundation",
     ["statistics", "probability", "statistical"])
_add("data_analysis", "Data Analysis (Pandas/Excel)", "data_science", "core",
     ["data analysis", "pandas", "excel", "data analytics"], ["python_basics"])
_add("data_visualization", "Data Visualization", "data_science", "core",
     ["data visualization", "tableau", "power bi", "matplotlib"], ["data_analysis"])
_add("machine_learning", "Machine Learning", "data_science", "core",
     ["machine learning", "scikit", "regression", "classification"],
     ["stats_foundations", "data_analysis"])
_add("deep_learning", "Deep Learning", "data_science", "advanced",
     ["deep learning", "neural network", "tensorflow", "pytorch", "cnn"], ["machine_learning"])
_add("nlp", "Natural Language Processing", "data_science", "advanced",
     ["nlp", "natural language processing", "text mining", "llm"], ["deep_learning"])
_add("data_science_capstone", "Data Science Career/Capstone", "data_science", "advanced",
     ["data scientist", "data science specialization", "capstone"], ["machine_learning"])

# ---- Web Development track ----
_add("html_css", "HTML & CSS", "web_dev", "foundation", ["html", "css", "web design"])
_add("javascript", "JavaScript", "web_dev", "core", ["javascript", "js"], ["html_css"])
_add("frontend_framework", "Frontend Framework (React/Angular/Vue)", "web_dev", "core",
     ["react", "angular", "vue", "frontend"], ["javascript"])
_add("backend_dev", "Backend Development (Node/Django/etc.)", "web_dev", "core",
     ["node.js", "django", "backend", "api development", "flask", "php"],
     ["javascript", "sql_databases"])
_add("fullstack_capstone", "Full-Stack Project / Capstone", "web_dev", "advanced",
     ["full stack", "web developer bootcamp", "mern", "mean stack"],
     ["frontend_framework", "backend_dev"])

# ---- Cloud / DevOps / Security ----
_add("cloud_fundamentals", "Cloud Fundamentals (AWS/GCP/Azure)", "cloud", "foundation",
     ["aws", "azure", "google cloud", "cloud computing"])
_add("devops", "DevOps & CI/CD", "cloud", "core",
     ["devops", "docker", "kubernetes", "ci/cd", "jenkins"], ["cloud_fundamentals"])
_add("cybersecurity", "Cybersecurity Fundamentals", "cybersecurity", "core",
     ["cyber security", "cybersecurity", "network security", "ethical hacking"])

# ---- Business / Finance ----
_add("finance_basics", "Finance Fundamentals", "business", "foundation",
     ["finance", "financial", "accounting", "investment banking"])
_add("business_analytics", "Business Analytics", "business", "core",
     ["business analytics", "business analysis"], ["finance_basics"])
_add("digital_marketing", "Digital Marketing", "business", "core",
     ["digital marketing", "seo", "social media marketing"])
_add("entrepreneurship", "Entrepreneurship", "business", "advanced",
     ["entrepreneurship", "startup"], ["finance_basics"])

# ---- Design ----
_add("design_basics", "Graphic Design Basics", "design", "foundation",
     ["graphic design", "design fundamentals", "illustrator", "photoshop"])
_add("ui_ux", "UI/UX Design", "design", "core",
     ["ui design", "ux design", "user experience", "figma"], ["design_basics"])


SUBTOPICS: dict[str, list[str]] = {
    "java_basics": [
        "Java Introduction and JDK Setup", "Java Syntax Variables and Data Types",
        "Java Operators and Type Casting", "Java Control Flow (if/else, switch)",
        "Java Loops (for, while, do-while)", "Java Arrays (1D and 2D)",
        "Java Strings and String Methods", "Java Methods and Parameter Passing",
        "Java OOP Classes and Objects", "Java Constructors and this Keyword",
        "Java Inheritance", "Java Polymorphism (Overloading and Overriding)",
        "Java Abstraction (Abstract Classes and Interfaces)",
        "Java Encapsulation and Access Modifiers",
        "Java Exception Handling (try/catch/finally)",
        "Java Collections Framework (List, Set, Map)", "Java Generics",
        "Java Multithreading and Concurrency", "Java File Handling and I/O Streams",
        "Java JDBC (Database Connectivity)",
        "Java 8 Lambda Expressions and Streams API", "Java Design Patterns Overview",
        "Java Build Tools (Maven/Gradle) Basics", "Java Unit Testing with JUnit",
    ],
    "dsa": [
        "Time and Space Complexity Big O", "Arrays and Strings", "Linked List",
        "Stacks and Queues", "Recursion and Backtracking",
        "Trees and Binary Search Trees", "Heaps and Priority Queues",
        "Hashing and Hash Maps", "Graphs BFS DFS",
        "Graph Algorithms (Dijkstra, Union-Find)", "Sorting Algorithms",
        "Searching Algorithms (Binary Search)", "Greedy Algorithms",
        "Dynamic Programming", "Sliding Window and Two Pointers",
    ],
    "python_basics": [
        "Python Syntax and Variables", "Python Data Types",
        "Python Control Flow (if/loops)", "Python Functions and Scope",
        "Python Data Structures (lists, tuples, dicts, sets)",
        "Python String Manipulation", "Python OOP Classes",
        "Python Exception Handling", "Python File Handling",
        "Python Modules and Packages", "Python Comprehensions and Generators",
        "Python Virtual Environments and pip",
    ],
    "javascript": [
        "JavaScript Variables and Data Types", "JavaScript Operators and Control Flow",
        "JavaScript Functions and Scope", "JavaScript Arrays and Objects",
        "JavaScript DOM Manipulation", "JavaScript Events",
        "JavaScript ES6 Features (let/const, arrow functions)",
        "JavaScript Destructuring and Spread Operator",
        "JavaScript Async/Await and Promises", "JavaScript Fetch API and AJAX",
        "JavaScript Error Handling", "JavaScript Modules (import/export)",
    ],
    "machine_learning": [
        "Introduction to Machine Learning", "Supervised vs Unsupervised Learning",
        "Linear Regression", "Logistic Regression",
        "Decision Trees and Random Forest", "Support Vector Machines",
        "K-Nearest Neighbors", "K-Means Clustering", "Model Evaluation Metrics",
        "Cross-Validation and Hyperparameter Tuning", "Feature Engineering",
        "Ensemble Methods (Bagging/Boosting)",
    ],
    "deep_learning": [
        "Neural Network Fundamentals", "Activation Functions",
        "Backpropagation Explained", "Convolutional Neural Networks (CNN)",
        "Recurrent Neural Networks (RNN/LSTM)", "Transfer Learning",
        "Regularization (Dropout, Batch Norm)", "Model Deployment Basics",
    ],
    "nlp": [
        "Text Preprocessing and Tokenization", "Bag of Words and TF-IDF",
        "Word Embeddings (Word2Vec)", "Transformers Explained",
        "Attention Mechanism", "Fine-tuning Language Models",
    ],
    "data_analysis": [
        "Pandas Basics", "Data Cleaning Techniques",
        "Exploratory Data Analysis (EDA)", "GroupBy and Aggregation in Pandas",
        "Merging and Joining DataFrames", "Handling Missing Data",
        "Excel for Data Analysis",
    ],
    "data_visualization": [
        "Matplotlib Basics", "Seaborn for Statistical Plots",
        "Tableau Fundamentals", "Power BI Fundamentals",
    ],
    "sql_databases": [
        "SQL SELECT and WHERE Basics", "SQL Joins Explained",
        "SQL Aggregate Functions and GROUP BY", "SQL Subqueries",
        "SQL Window Functions", "Database Normalization",
        "Indexes and Query Optimization",
    ],
    "html_css": [
        "HTML Basics and Structure", "HTML Forms and Semantic Tags",
        "CSS Selectors and Box Model", "CSS Flexbox", "CSS Grid",
        "CSS Animations and Transitions", "Responsive Web Design",
    ],
    "frontend_framework": [
        "React Fundamentals (Components, Props)", "React State and Hooks",
        "React Routing", "React Forms and Controlled Inputs",
        "State Management (Redux/Context)", "React Performance Optimization",
    ],
    "backend_dev": [
        "REST API Fundamentals", "Node.js and Express Basics",
        "Middleware and Routing", "Authentication (JWT/OAuth)",
        "Connecting Backend to Database", "API Error Handling and Validation",
    ],
    "cloud_fundamentals": [
        "Cloud Computing Basics (IaaS/PaaS/SaaS)", "AWS EC2 and S3 Basics",
        "Cloud Networking Fundamentals", "Cloud Storage and Databases",
        "Cloud Security Basics",
    ],
    "devops": [
        "Docker Fundamentals", "Docker Compose", "Kubernetes Basics",
        "CI/CD Pipeline Concepts", "Jenkins Tutorial",
        "Infrastructure as Code Basics",
    ],
    "cybersecurity": [
        "Cybersecurity Fundamentals", "Network Security Basics",
        "Ethical Hacking Introduction", "Common Web Vulnerabilities (OWASP)",
        "Cryptography Basics",
    ],
    "stats_foundations": [
        "Descriptive Statistics", "Probability Basics", "Probability Distributions",
        "Hypothesis Testing", "Correlation and Regression Basics",
    ],
    "finance_basics": [
        "Financial Accounting Basics", "Financial Statements Explained",
        "Time Value of Money", "Investment Banking Basics", "Ratio Analysis",
    ],
    "digital_marketing": [
        "SEO Fundamentals", "Social Media Marketing Basics",
        "Google Ads Fundamentals", "Content Marketing Strategy",
        "Email Marketing Basics",
    ],
    "design_basics": [
        "Design Principles and Color Theory", "Typography Basics",
        "Adobe Photoshop Basics", "Adobe Illustrator Basics",
    ],
    "ui_ux": [
        "UX Design Process", "Wireframing and Prototyping", "Figma Tutorial",
        "Design Systems Basics", "Usability Testing Basics",
    ],
    "cpp_basics": [
        "C++ Syntax and Variables", "C++ Control Flow",
        "C++ Functions and Pointers", "C++ OOP Concepts",
        "C++ STL (Standard Template Library)", "C++ Memory Management",
    ],
    "git_version_control": [
        "Git Basics (init, add, commit)", "Git Branching and Merging",
        "GitHub Pull Requests", "Resolving Git Merge Conflicts",
    ],
    "android_dev": [
        "Android Studio Setup", "Android UI Layouts (XML)",
        "Android Activities and Intents", "Android RecyclerView",
        "Android App with Firebase/Room DB",
    ],
    "data_science_capstone": [
        "Framing a Data Science Problem Statement", "End-to-End EDA on a Real Dataset",
        "Feature Engineering for a Capstone Project", "Model Selection and Comparison",
        "Building a Results Dashboard (Streamlit/Power BI)",
        "Writing Up and Presenting Data Science Findings",
        "Deploying a Model as an API", "Portfolio-Ready Case Study Documentation",
    ],
    "fullstack_capstone": [
        "Planning a Full-Stack App Architecture", "Designing the Database Schema",
        "Building the REST API Layer", "Connecting Frontend to Backend",
        "Authentication and Authorization End-to-End", "Deployment (Frontend + Backend + DB)",
        "Writing Tests for a Full-Stack App", "Polishing UI/UX for a Portfolio Project",
    ],
    "business_analytics": [
        "Business Analytics Fundamentals", "KPI and Metric Design",
        "Data-Driven Decision Making", "Dashboarding for Business Stakeholders (Power BI/Tableau)",
        "A/B Testing Basics", "Business Case Study Analysis",
    ],
    "entrepreneurship": [
        "Ideation and Problem Validation", "Business Model Canvas",
        "Market Research Basics", "MVP Planning and Lean Startup",
        "Pitching and Fundraising Basics", "Unit Economics Fundamentals",
    ],
}


def get_subtopics(skill_id: str, label: str) -> list[str]:
    return SUBTOPICS.get(skill_id, [label])


def shortest_learning_order(start_known: list[str], goal_id: str) -> list[str]:
    """
    Ancestors of goal_id (all transitive prerequisites), minus anything the
    learner already knows, topologically sorted (Kahn's algorithm) so every
    dependency comes before what depends on it.
    """
    if goal_id not in SKILLS:
        return []
    known = set(start_known)

    ancestors: set[str] = set()

    def collect(sid: str) -> None:
        for p in SKILLS[sid].prereqs:
            if p not in ancestors:
                ancestors.add(p)
                collect(p)

    collect(goal_id)
    ancestors.add(goal_id)

    needed = [sid for sid in ancestors if sid not in known]
    needed_set = set(needed)

    in_degree = {sid: 0 for sid in needed}
    adj: dict[str, list[str]] = {sid: [] for sid in needed}
    for sid in needed:
        for p in SKILLS[sid].prereqs:
            if p in needed_set:
                adj[p].append(sid)
                in_degree[sid] += 1

    queue = [sid for sid in needed if in_degree[sid] == 0]
    order: list[str] = []
    while queue:
        sid = queue.pop(0)
        order.append(sid)
        for nxt in adj[sid]:
            in_degree[nxt] -= 1
            if in_degree[nxt] == 0:
                queue.append(nxt)

    return order if len(order) == len(needed) else needed


# ---- Career paths shown on the onboarding / profile screen ----
# Each maps to a "goal skill" in the DAG above -- the path generator walks
# backwards from this skill to whatever the learner already knows.
CAREER_PATHS = [
    {"id": "web_dev", "label": "Web Development", "domain": "web_dev",
     "goal_skill": "fullstack_capstone",
     "description": "Front-end, back-end, and full-stack web engineering."},
    {"id": "ai_ml", "label": "AI / Machine Learning", "domain": "data_science",
     "goal_skill": "deep_learning",
     "description": "Machine learning, deep learning, and applied AI."},
    {"id": "data_science", "label": "Data Science & Analytics", "domain": "data_science",
     "goal_skill": "data_science_capstone",
     "description": "Data analysis, visualization, and statistical modeling."},
    {"id": "cybersecurity", "label": "Cybersecurity", "domain": "cybersecurity",
     "goal_skill": "cybersecurity",
     "description": "Network security, ethical hacking, and defensive security."},
    {"id": "cloud_devops", "label": "Cloud & DevOps", "domain": "cloud",
     "goal_skill": "devops",
     "description": "Cloud infrastructure, containers, and CI/CD pipelines."},
    {"id": "mobile_dev", "label": "Mobile App Development", "domain": "programming",
     "goal_skill": "android_dev",
     "description": "Native Android app development with Java/Kotlin."},
    {"id": "ui_ux_design", "label": "UI/UX Design", "domain": "design",
     "goal_skill": "ui_ux",
     "description": "Product design, prototyping, and user research."},
    {"id": "business_analytics", "label": "Business & Analytics", "domain": "business",
     "goal_skill": "business_analytics",
     "description": "Finance, business analysis, and entrepreneurship."},
    {"id": "other", "label": "Something else", "domain": "custom",
     "goal_skill": None,
     "description": "Tell us your goal in your own words and we'll match it."},
]

CAREER_PATH_BY_ID = {c["id"]: c for c in CAREER_PATHS}
